/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vegbgptomnevhtgicpcy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlZ2JncHRvbW5ldmh0Z2ljcGN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwNTI1NzEsImV4cCI6MjA4NTYyODU3MX0.nx3-hm2sKtwaO3H0Rs_KecDHs0vlH-S-TOjUrV2qHqQ"